/*
 * ACH API
 *
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// Batch struct for Batch
type Batch struct {
	BatchHeader  BatchHeader   `json:"batchHeader,omitempty"`
	EntryDetails []EntryDetail `json:"entryDetails,omitempty"`
	BatchControl BatchControl  `json:"batchControl,omitempty"`
}
