/*
 * ACH API
 *
 * Moov ACH ([Automated Clearing House](https://en.wikipedia.org/wiki/Automated_Clearing_House)) implements an HTTP API for creating, parsing and validating ACH files. ACH is the primary method of electronic money movement throughout the United States.
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package client

// FileHeader struct for FileHeader
type FileHeader struct {
	// contains the Routing Number of the ACH Operator or sending point that is sending the file.
	ImmediateOrigin string `json:"immediateOrigin"`
	// The name of the ACH operator or sending point that is sending the file.
	ImmediateOriginName string `json:"immediateOriginName"`
	// contains the Routing Number of the ACH Operator or receiving point to which the file is being sent
	ImmediateDestination string `json:"immediateDestination"`
	// The name of the ACH or receiving point for which that file is destined.
	ImmediateDestinationName string `json:"immediateDestinationName"`
	// The File Creation Date is the date when the file was prepared by an ODFI. (Format HHmm - H=Hour, m=Minute)
	FileCreationTime string `json:"fileCreationTime,omitempty"`
	// The File Creation Time is the time when the file was prepared by an ODFI. (Format YYMMDD - Y=Year, M=Month, D=Day)
	FileCreationDate string `json:"fileCreationDate,omitempty"`
	// Incremented value for each file for RDFI's.
	FileIDModifier string `json:"fileIDModifier,omitempty"`
}
