# Step one: build scapresults
FROM registry.access.redhat.com/ubi9/go-toolset as builder
COPY go.mod go.mod
COPY go.sum go.sum
COPY *.go ./
COPY ./cmd/server ./cmd/server
COPY ./examples ./examples
COPY ./internal ./internal
COPY ./server ./server
COPY ./test ./test
COPY makefile makefile
RUN make build

FROM registry.access.redhat.com/ubi9/ubi-minimal:9.5-1731604394
ARG VERSION=unknown
LABEL maintainer="Moov <oss@moov.io>"
LABEL name="ach"
LABEL version=$VERSION

COPY --from=builder /opt/app-root/src/bin/server /bin/server

EXPOSE 8080
EXPOSE 9090
ENTRYPOINT ["/bin/server"]
