# Step one: build scapresults
FROM registry.access.redhat.com/ubi8/go-toolset as builder
COPY . .
RUN make build

FROM registry.access.redhat.com/ubi8/ubi-minimal

ARG VERSION=unknown
LABEL maintainer="Moov <oss@moov.io>"
LABEL name="ach"
LABEL version=$VERSION

COPY --from=builder /opt/app-root/src/bin/server /bin/server

EXPOSE 8080
EXPOSE 9090
ENTRYPOINT ["/bin/server"]
