FROM golang:1.18 as builder
LABEL maintainer="Moov <support@moov.io>"
RUN apt-get update -qq && apt-get install -y git make
WORKDIR /go/src/github.com/moov-io/ach
COPY . .
RUN go mod download && go mod vendor
WORKDIR /go/src/github.com/moov-io/ach/test/fuzz-reader
RUN make install
RUN make fuzz-build
ENTRYPOINT make fuzz-run
