---
name: Report an issue
description:
  Tell us about something that is not working the way we (probably) intend
body:
  - type: textarea
    id: ach-version
    attributes:
      label: ACH Version
      description: What version of ACH are you using?
    validations:
      required: true

  - type: textarea
    id: intention
    attributes:
      label: What were you trying to do?
      description: >
        Describe how you were using the ACH library. Include code samples,
        errors, and stacktraces if appropriate.
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to see?
      description: >
        A short description on how you expect the code to behave.
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: What did you see?
      description: Share any logs, errors, or stacktraces that you saw.
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: How can we reproduce the problem?
      description: Help us reproduce the problem by sharing a minimal example.
    validations:
      required: true
