source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "bulma-clean-theme"
gem "jekyll", "~> 3.10"
# github-pages 232 pins jekyll-remote-theme 0.4.3, which requires rubyzip < 3.0
# (CVE-2026-85396, GHSA-47m2-wp7j-p9vc). Pin a remote-theme that allows rubyzip 3.4+.
gem "jekyll-remote-theme", ">= 0.5.2"
gem "kramdown-parser-gfm"
gem "webrick"
gem "rubyzip", ">= 3.4.0"
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.17"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", "~> 2.0"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.2.0", :platforms => [:mingw, :x64_mingw, :mswin]
